// Code generated by bencgen golang. DO NOT EDIT.
// source: schema.benc

package dbm

import (
    "github.com/deneonet/benc/std"
    "github.com/deneonet/benc/impl/gen"
)

// Struct - TestObj
type TestObj struct {
    I int
    S string
}

// Reserved Ids - TestObj
var testObjRIds = []uint16{}

// Size - TestObj
func (testObj *TestObj) Size() int {
    return testObj.size(0)
}

// Nested Size - TestObj
func (testObj *TestObj) size(id uint16) (s int) {
    s += bstd.SizeInt(testObj.I) + 2
    s += bstd.SizeString(testObj.S) + 2

    if id > 255 {
        s += 5
        return
    }
    s += 4
    return
}

// SizePlain - TestObj
func (testObj *TestObj) SizePlain() (s int) {
    s += bstd.SizeInt(testObj.I)
    s += bstd.SizeString(testObj.S)
    return
}

// Marshal - TestObj
func (testObj *TestObj) Marshal(b []byte) {
    testObj.marshal(0, b, 0)
}

// Nested Marshal - TestObj
func (testObj *TestObj) marshal(tn int, b []byte, id uint16) (n int) {
    n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Varint, 1)
    n = bstd.MarshalInt(n, b, testObj.I)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 2)
    n = bstd.MarshalString(n, b, testObj.S)

    n += 2
    b[n-2] = 1
    b[n-1] = 1
    return
}

// MarshalPlain - TestObj
func (testObj *TestObj) MarshalPlain(tn int, b []byte) (n int) {
    n = tn
    n = bstd.MarshalInt(n, b, testObj.I)
    n = bstd.MarshalString(n, b, testObj.S)
    return n
}

// Unmarshal - TestObj
func (testObj *TestObj) Unmarshal(b []byte) (err error) {
    _, err = testObj.unmarshal(0, b, []uint16{}, 0)
    return
}

// Nested Unmarshal - TestObj
func (testObj *TestObj) unmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
    var ok bool
    if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, testObjRIds, 1); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, testObj.I, err = bstd.UnmarshalInt(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, testObjRIds, 2); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, testObj.S, err = bstd.UnmarshalString(n, b); err != nil {
            return
        }
    }
    n += 2
    return
}

// UnmarshalPlain - TestObj
func (testObj *TestObj) UnmarshalPlain(tn int, b []byte) (n int, err error) {
    n = tn
    if n, testObj.I, err = bstd.UnmarshalInt(n, b); err != nil {
        return
    }
    if n, testObj.S, err = bstd.UnmarshalString(n, b); err != nil {
        return
    }
    return
}

